### ISSUE TITLE
Anipose tutorial

### ISSUE THREAD

**Issue by miahoffmannd** [lambdaloop/anipose#126]
The tutorial no longer works with the specified python and tensorflow versions. I got the following error message when working in an environment with python=3.7 and tensorflow=1.13.1

  from tensorflow.python.framework import device_spec as tf_device
ImportError: cannot import name 'device_spec' from 'tensorflow.python.framework' (C:\Users\XXX\anaconda3\envs\yourevname\lib\site-packages\tensorflow\python\framework\__init__.py)

**Comment by jomuecke** [comment]
@miahoffmannd https://github.com/lambdaloop/anipose/issues/118
